import mongoose from "mongoose";
import dotenv from "dotenv";
import Applicant from "./models/applicant.model";
import Job from "./models/job.model";

dotenv.config();

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI!);
    console.log("Connected to MongoDB");

    const jobs = await Job.find({});
    if (jobs.length === 0) {
      console.log("No jobs found! Please create jobs first.");
      process.exit(1);
    }

    console.log(`Found ${jobs.length} existing jobs:`);
    jobs.forEach(j => console.log(` - ${j.title} (${j._id})`));

    await Applicant.deleteMany({});
    console.log("Cleared existing applicants");

    const jobMap: Record<string, any> = {};
    jobs.forEach(j => { jobMap[j.title] = j._id; });

    const allApplicants: any[] = [];

    jobs.forEach(job => {
      const id = job._id;
      const title = job.title;

      if (title.toLowerCase().includes("software") || title.toLowerCase().includes("developer") || title.toLowerCase().includes("engineer") && !title.toLowerCase().includes("devops")) {
        allApplicants.push(...[
          { name: "Alice Uwimana", email: "alice@email.com", phone: "+250781234567", currentPosition: "Software Engineer", jobTitle: "Software Engineer", yearsOfExperience: 4, experienceYears: 4, educationLevel: "BSc Computer Science", summary: "4 years building production web apps with React and Node.js.", skills: ["React", "Node.js", "TypeScript", "MongoDB", "AWS", "Docker"], certifications: ["AWS Certified Developer", "Google Cloud Professional"], projects: ["E-commerce platform 10k users", "Real-time chat app", "HR Management System"], githubUrl: "https://github.com/alice", portfolioUrl: "https://alice.dev", jobId: id, source: "external", status: "submitted" },
          { name: "Bob Nkurunziza", email: "bob@email.com", phone: "+250782345678", currentPosition: "Junior Developer", jobTitle: "Junior Developer", yearsOfExperience: 1, experienceYears: 1, educationLevel: "Bachelor Degree", summary: "Junior developer learning fast and eager to grow.", skills: ["React", "JavaScript", "CSS"], certifications: [], projects: ["Personal portfolio website"], githubUrl: "https://github.com/bob", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Claire Mukamana", email: "claire@email.com", phone: "+250783456789", currentPosition: "Full Stack Developer", jobTitle: "Full Stack Developer", yearsOfExperience: 3, experienceYears: 3, educationLevel: "BSc Software Engineering", summary: "Full stack developer with strong React and Node.js background.", skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "Docker"], certifications: ["AWS Solutions Architect"], projects: ["Banking dashboard", "Food delivery platform", "School management system"], githubUrl: "https://github.com/claire", portfolioUrl: "https://claire.dev", jobId: id, source: "external", status: "submitted" },
          { name: "David Habimana", email: "david@email.com", phone: "+250784567890", currentPosition: "Backend Engineer", jobTitle: "Backend Engineer", yearsOfExperience: 5, experienceYears: 5, educationLevel: "MSc Computer Science", summary: "Senior backend engineer building scalable microservices for 5 years.", skills: ["Node.js", "TypeScript", "MongoDB", "AWS", "Docker", "Kubernetes", "Redis"], certifications: ["AWS Certified Solutions Architect", "Docker Certified Associate", "Google Cloud Professional"], projects: ["Microservices for fintech", "API gateway 1M requests/day", "Real-time analytics platform"], githubUrl: "https://github.com/david", portfolioUrl: "https://david.dev", jobId: id, source: "external", status: "submitted" },
          { name: "Eve Ishimwe", email: "eve@email.com", phone: "+250785678901", currentPosition: "Software Developer", jobTitle: "Software Developer", yearsOfExperience: 2, experienceYears: 2, educationLevel: "BSc Information Technology", summary: "Software developer with 2 years web development experience.", skills: ["React", "Node.js", "MongoDB", "Git"], certifications: ["Meta Frontend Developer"], projects: ["Hospital management system", "Online voting platform"], githubUrl: "https://github.com/eve", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Fiston Niyonsenga", email: "fiston@email.com", phone: "+250786789012", currentPosition: "Mid-level Developer", jobTitle: "Mid-level Developer", yearsOfExperience: 3, experienceYears: 3, educationLevel: "BSc Computer Science", summary: "Mid-level developer with strong TypeScript and cloud skills.", skills: ["React", "TypeScript", "Node.js", "AWS", "MongoDB"], certifications: ["AWS Developer Associate"], projects: ["SaaS subscription platform", "Mobile API backend"], githubUrl: "https://github.com/fiston", portfolioUrl: "https://fiston.dev", jobId: id, source: "external", status: "submitted" },
          { name: "Grace Uwamariya", email: "grace2@email.com", phone: "+250787890123", currentPosition: "Frontend Developer", jobTitle: "Frontend Developer", yearsOfExperience: 2, experienceYears: 2, educationLevel: "BSc Computer Science", summary: "Frontend developer passionate about accessible, responsive UIs.", skills: ["React", "TypeScript", "CSS", "GraphQL"], certifications: ["AWS Cloud Practitioner"], projects: ["Healthcare portal", "Real estate listing app"], githubUrl: "https://github.com/grace", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Henry Mugisha", email: "henry@email.com", phone: "+250788901234", currentPosition: "Web Developer", jobTitle: "Web Developer", yearsOfExperience: 1, experienceYears: 1, educationLevel: "Diploma", summary: "Self-taught web developer passionate about frontend.", skills: ["React", "CSS", "JavaScript"], certifications: [], projects: ["Personal blog", "Weather app"], githubUrl: "https://github.com/henry", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Irene Mukamwiza", email: "irene@email.com", phone: "+250789012345", currentPosition: "Software Engineer", jobTitle: "Software Engineer", yearsOfExperience: 4, experienceYears: 4, educationLevel: "BSc Software Engineering", summary: "Software engineer with fintech experience and strong AWS skills.", skills: ["Node.js", "TypeScript", "AWS", "Docker", "MongoDB", "React"], certifications: ["AWS Certified Developer", "Kubernetes Application Developer"], projects: ["Payment gateway integration", "Loan management system", "Admin dashboard for bank"], githubUrl: "https://github.com/irene", portfolioUrl: "https://irene.dev", jobId: id, source: "external", status: "submitted" },
          { name: "Jules Nzeyimana", email: "jules@email.com", phone: "+250780123456", currentPosition: "DevOps & Backend Engineer", jobTitle: "DevOps & Backend Engineer", yearsOfExperience: 6, experienceYears: 6, educationLevel: "MSc Computer Science", summary: "6 years experience in backend engineering and cloud infrastructure.", skills: ["Node.js", "TypeScript", "MongoDB", "AWS", "Docker", "Kubernetes", "Redis", "GraphQL", "CI/CD"], certifications: ["AWS Solutions Architect Professional", "Docker Certified Associate", "CKA", "Google Cloud Professional"], projects: ["Platform handling 5M users", "Microservices migration from monolith", "Realtime notification system"], githubUrl: "https://github.com/jules", portfolioUrl: "https://jules.io", jobId: id, source: "external", status: "submitted" },
          { name: "Kagiso Murenzi", email: "kagiso@email.com", phone: "+250781234568", currentPosition: "Junior Software Engineer", jobTitle: "Junior Software Engineer", yearsOfExperience: 0, experienceYears: 0, educationLevel: "BSc Computer Science", summary: "Fresh graduate with strong academic background and internship experience.", skills: ["React", "JavaScript", "Node.js"], certifications: ["Meta Frontend Developer"], projects: ["Final year project: inventory management system"], githubUrl: "https://github.com/kagiso", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Laeticia Ingabire", email: "laeticia@email.com", phone: "+250782345679", currentPosition: "Software Engineer", jobTitle: "Software Engineer", yearsOfExperience: 3, experienceYears: 3, educationLevel: "BSc Computer Science", summary: "Software engineer with 3 years in React and Node.js building SaaS products.", skills: ["React", "Node.js", "TypeScript", "MongoDB", "AWS"], certifications: ["AWS Certified Developer"], projects: ["CRM system for SMEs", "Job board platform", "Budget tracker app"], githubUrl: "https://github.com/laeticia", portfolioUrl: "https://laeticia.dev", jobId: id, source: "external", status: "submitted" },
        ]);
      }

      if (title.toLowerCase().includes("product manager")) {
        allApplicants.push(...[
          { name: "Fabrice Ndayisenga", email: "fabrice@email.com", phone: "+250786789013", currentPosition: "Product Manager", jobTitle: "Product Manager", yearsOfExperience: 4, experienceYears: 4, educationLevel: "MBA", summary: "PM with 4 years launching digital products from 0 to 1.", skills: ["Product Strategy", "Agile", "User Research", "Roadmapping", "Stakeholder Management", "Jira"], certifications: ["Certified Scrum Product Owner", "Google Project Management"], projects: ["Launched fintech app 50k users", "Reduced onboarding drop-off 40%"], githubUrl: "", portfolioUrl: "https://fabrice.pm", jobId: id, source: "external", status: "submitted" },
          { name: "Gisele Umutoniwase", email: "gisele@email.com", phone: "+250787890124", currentPosition: "Business Analyst", jobTitle: "Business Analyst", yearsOfExperience: 2, experienceYears: 2, educationLevel: "Bachelor Degree", summary: "Business analyst transitioning to product management.", skills: ["User Research", "Agile", "Roadmapping", "Excel"], certifications: ["Google Project Management"], projects: ["User research for 3 products", "Roadmap for internal tool"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Herve Kayitare", email: "herve@email.com", phone: "+250788901235", currentPosition: "Senior Product Manager", jobTitle: "Senior Product Manager", yearsOfExperience: 6, experienceYears: 6, educationLevel: "MBA", summary: "Senior PM with 6 years in SaaS and mobile products.", skills: ["Product Strategy", "Agile", "User Research", "Roadmapping", "Stakeholder Management", "A/B Testing", "SQL"], certifications: ["Certified Scrum Product Owner", "Product School Certification", "Google Analytics"], projects: ["Platform with 200k users", "Grew revenue 35%", "Company-wide analytics dashboard"], githubUrl: "", portfolioUrl: "https://herve.pm", jobId: id, source: "external", status: "submitted" },
          { name: "Ines Mukandoli", email: "ines@email.com", phone: "+250789012346", currentPosition: "Project Coordinator", jobTitle: "Project Coordinator", yearsOfExperience: 1, experienceYears: 1, educationLevel: "Bachelor Degree", summary: "Project coordinator looking to grow into product management.", skills: ["Agile", "Stakeholder Management", "Excel"], certifications: [], projects: ["Coordinated 5 software projects on time"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Josiane Nyiransabimana", email: "josiane@email.com", phone: "+250780123457", currentPosition: "Associate Product Manager", jobTitle: "Associate Product Manager", yearsOfExperience: 2, experienceYears: 2, educationLevel: "Bachelor Degree", summary: "Associate PM with 2 years experience in mobile and web products.", skills: ["Product Strategy", "Agile", "User Research", "Roadmapping", "Figma"], certifications: ["Google Project Management", "Scrum Master"], projects: ["Shipped 3 mobile app features", "Conducted 20+ user interviews"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Kevin Ntwari", email: "kevin@email.com", phone: "+250781234569", currentPosition: "Product Lead", jobTitle: "Product Lead", yearsOfExperience: 5, experienceYears: 5, educationLevel: "MBA", summary: "Product lead with 5 years building data-driven products.", skills: ["Product Strategy", "Agile", "User Research", "Roadmapping", "Stakeholder Management", "SQL", "Mixpanel"], certifications: ["Certified Scrum Product Owner", "Product School", "Google Analytics", "Amplitude Certified"], projects: ["0 to 100k users product launch", "A/B testing framework that increased conversion 25%", "Product analytics setup for company"], githubUrl: "", portfolioUrl: "https://kevin.pm", jobId: id, source: "external", status: "submitted" },
          { name: "Liliane Uwineza", email: "liliane@email.com", phone: "+250782345680", currentPosition: "Product Manager", jobTitle: "Product Manager", yearsOfExperience: 3, experienceYears: 3, educationLevel: "Bachelor Degree", summary: "Product manager with 3 years in fintech and e-commerce.", skills: ["Product Strategy", "Agile", "User Research", "Roadmapping", "Stakeholder Management"], certifications: ["Certified Scrum Product Owner"], projects: ["Mobile wallet product", "E-commerce checkout redesign"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Martin Ndahiro", email: "martin@email.com", phone: "+250783456791", currentPosition: "Junior Product Manager", jobTitle: "Junior Product Manager", yearsOfExperience: 1, experienceYears: 1, educationLevel: "Bachelor Degree", summary: "Junior PM eager to build great products.", skills: ["Agile", "User Research", "Roadmapping"], certifications: ["Google Project Management"], projects: ["Feature discovery for SaaS tool"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
        ]);
      }

      if (title.toLowerCase().includes("design") || title.toLowerCase().includes("ux") || title.toLowerCase().includes("ui")) {
        allApplicants.push(...[
          { name: "Jean-Pierre Nzabonimpa", email: "jp@email.com", phone: "+250784567893", currentPosition: "UX Designer", jobTitle: "UX Designer", yearsOfExperience: 3, experienceYears: 3, educationLevel: "Bachelor Degree", summary: "UX designer building user-centered products for 3 years.", skills: ["Figma", "User Research", "Prototyping", "Design Systems", "Adobe XD"], certifications: ["Google UX Design", "Figma Advanced"], projects: ["Design system 80 components", "Mobile app redesign +60% engagement", "UX audit e-commerce"], githubUrl: "", portfolioUrl: "https://jp.design", jobId: id, source: "external", status: "submitted" },
          { name: "Keza Ingabire", email: "keza@email.com", phone: "+250785678904", currentPosition: "Graphic Designer", jobTitle: "Graphic Designer", yearsOfExperience: 2, experienceYears: 2, educationLevel: "Bachelor Degree", summary: "Graphic designer expanding into UX/UI design.", skills: ["Figma", "Adobe XD", "Prototyping"], certifications: ["Google UX Design Certificate"], projects: ["Branding for 3 startups", "Mobile app mockup for NGO"], githubUrl: "", portfolioUrl: "https://keza.design", jobId: id, source: "external", status: "submitted" },
          { name: "Leon Nshimiyimana", email: "leon@email.com", phone: "+250786789015", currentPosition: "Junior UI Designer", jobTitle: "Junior UI Designer", yearsOfExperience: 1, experienceYears: 1, educationLevel: "Diploma", summary: "Junior UI designer with a strong eye for clean interfaces.", skills: ["Figma", "Prototyping"], certifications: [], projects: ["Portfolio website design", "Restaurant menu app UI"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Marie Uwimana", email: "marie@email.com", phone: "+250787890126", currentPosition: "Senior UX Designer", jobTitle: "Senior UX Designer", yearsOfExperience: 5, experienceYears: 5, educationLevel: "MSc Computer Science", summary: "Senior UX designer with deep research and design systems expertise.", skills: ["Figma", "User Research", "Prototyping", "Design Systems", "Adobe XD", "Usability Testing"], certifications: ["Google UX Design", "Interaction Design Foundation", "Figma Advanced"], projects: ["Platform UX for 100k users", "Company-wide design system", "50+ user interviews"], githubUrl: "", portfolioUrl: "https://marie.design", jobId: id, source: "external", status: "submitted" },
          { name: "Noela Cyubahiro", email: "noela@email.com", phone: "+250788901237", currentPosition: "UI/UX Designer", jobTitle: "UI/UX Designer", yearsOfExperience: 3, experienceYears: 3, educationLevel: "Bachelor Degree", summary: "UI/UX designer with strong skills in both visual design and user research.", skills: ["Figma", "User Research", "Prototyping", "Design Systems"], certifications: ["Google UX Design", "Adobe Certified Professional"], projects: ["Redesigned onboarding flow reducing drop-off 50%", "Mobile app for agricultural marketplace", "Dashboard UI for analytics platform"], githubUrl: "", portfolioUrl: "https://noela.design", jobId: id, source: "external", status: "submitted" },
          { name: "Oscar Mugwaneza", email: "oscar@email.com", phone: "+250789012347", currentPosition: "Product Designer", jobTitle: "Product Designer", yearsOfExperience: 4, experienceYears: 4, educationLevel: "Bachelor Degree", summary: "Product designer bridging UX research and visual design.", skills: ["Figma", "User Research", "Prototyping", "Design Systems", "Adobe XD", "Webflow"], certifications: ["Google UX Design", "Figma Advanced", "Interaction Design Foundation"], projects: ["End-to-end product design for fintech app", "User research report for government portal", "Webflow site for 10k monthly visitors"], githubUrl: "", portfolioUrl: "https://oscar.design", jobId: id, source: "external", status: "submitted" },
          { name: "Prudence Umubyeyi", email: "prudence@email.com", phone: "+250780123458", currentPosition: "Freelance UI Designer", jobTitle: "Freelance UI Designer", yearsOfExperience: 2, experienceYears: 2, educationLevel: "Diploma", summary: "Freelance UI designer with a portfolio of client projects.", skills: ["Figma", "Adobe XD"], certifications: [], projects: ["10+ client websites", "Mobile UI for local transport app"], githubUrl: "", portfolioUrl: "https://prudence.design", jobId: id, source: "external", status: "submitted" },
        ]);
      }

      if (title.toLowerCase().includes("devops")) {
        allApplicants.push(...[
          { name: "Nathan Bizimana", email: "nathan@email.com", phone: "+250784567894", currentPosition: "DevOps Engineer", jobTitle: "DevOps Engineer", yearsOfExperience: 4, experienceYears: 4, educationLevel: "BSc Computer Science", summary: "DevOps engineer automating infrastructure and deployments for 4 years.", skills: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD", "Linux", "Python"], certifications: ["AWS Certified DevOps Engineer", "Certified Kubernetes Administrator", "Terraform Associate"], projects: ["Zero-downtime deployment pipeline", "Auto-scaling saving 40% costs", "Monitoring for 20 microservices"], githubUrl: "https://github.com/nathan", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Olive Nyiramana", email: "olive@email.com", phone: "+250785678905", currentPosition: "Systems Administrator", jobTitle: "Systems Administrator", yearsOfExperience: 2, experienceYears: 2, educationLevel: "BSc Information Technology", summary: "Sysadmin moving into DevOps with strong Linux and cloud skills.", skills: ["Linux", "Docker", "CI/CD", "AWS"], certifications: ["AWS Cloud Practitioner", "Linux Foundation Certified Sysadmin"], projects: ["Migrated 10 servers to cloud", "CI/CD pipeline for dev team"], githubUrl: "https://github.com/olive", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Patrick Mugabo", email: "patrick@email.com", phone: "+250786789016", currentPosition: "Cloud Engineer", jobTitle: "Cloud Engineer", yearsOfExperience: 5, experienceYears: 5, educationLevel: "BSc Computer Science", summary: "Cloud engineer specialized in AWS and Kubernetes at scale.", skills: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD", "Linux", "Ansible", "Prometheus"], certifications: ["AWS Solutions Architect Professional", "CKA", "Terraform Associate", "Google Cloud DevOps"], projects: ["Multi-cloud infra for 10M users", "Kubernetes cluster 500 pods", "Disaster recovery 15min RTO"], githubUrl: "https://github.com/patrick", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Qatarina Uwamahoro", email: "qatarina@email.com", phone: "+250787890127", currentPosition: "Cloud Support Engineer", jobTitle: "Cloud Support Engineer", yearsOfExperience: 2, experienceYears: 2, educationLevel: "BSc Computer Science", summary: "Cloud support engineer with hands-on AWS and Docker experience.", skills: ["AWS", "Docker", "Linux", "CI/CD"], certifications: ["AWS Cloud Practitioner", "Docker Fundamentals"], projects: ["Deployed containerized apps on AWS", "Set up CloudWatch monitoring dashboards"], githubUrl: "https://github.com/qatarina", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Richard Nkusi", email: "richard@email.com", phone: "+250788901238", currentPosition: "Infrastructure Engineer", jobTitle: "Infrastructure Engineer", yearsOfExperience: 3, experienceYears: 3, educationLevel: "BSc Computer Science", summary: "Infrastructure engineer with Terraform and Kubernetes expertise.", skills: ["AWS", "Docker", "Kubernetes", "Terraform", "Linux", "CI/CD"], certifications: ["AWS Certified SysOps Administrator", "Certified Kubernetes Administrator"], projects: ["IaC migration using Terraform", "Kubernetes deployment for SaaS app", "Blue-green deployment pipeline"], githubUrl: "https://github.com/richard", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Serge Niyomwungeri", email: "serge@email.com", phone: "+250789012348", currentPosition: "Junior DevOps Engineer", jobTitle: "Junior DevOps Engineer", yearsOfExperience: 1, experienceYears: 1, educationLevel: "BSc Information Technology", summary: "Junior DevOps engineer with internship experience.", skills: ["Docker", "Linux", "CI/CD"], certifications: [], projects: ["Set up GitHub Actions pipeline for internship project"], githubUrl: "https://github.com/serge", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Therese Uwingabire", email: "therese@email.com", phone: "+250780123459", currentPosition: "Senior DevOps Engineer", jobTitle: "Senior DevOps Engineer", yearsOfExperience: 7, experienceYears: 7, educationLevel: "MSc Computer Science", summary: "Senior DevOps engineer with 7 years building world-class infrastructure.", skills: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD", "Linux", "Ansible", "Prometheus", "Grafana", "Vault"], certifications: ["AWS Solutions Architect Professional", "CKA", "Terraform Associate", "Google Cloud Professional DevOps", "HashiCorp Vault"], projects: ["Global infra for platform in 15 countries", "Cost optimization saving $500k/year", "Security-hardened Kubernetes cluster"], githubUrl: "https://github.com/therese", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
        ]);
      }

      if (title.toLowerCase().includes("marketing")) {
        allApplicants.push(...[
          { name: "Queen Mukeshimana", email: "queen@email.com", phone: "+250787890128", currentPosition: "Digital Marketing Specialist", jobTitle: "Digital Marketing Specialist", yearsOfExperience: 3, experienceYears: 3, educationLevel: "Bachelor Degree", summary: "Digital marketer with proven SEO and content results.", skills: ["Digital Marketing", "SEO", "Content Strategy", "Social Media", "Google Analytics"], certifications: ["Google Digital Marketing", "HubSpot Content Marketing", "Meta Blueprint"], projects: ["Grew organic traffic 200% in 6 months", "Social campaign 500k reach", "Email campaign 35% open rate"], githubUrl: "", portfolioUrl: "https://queen.marketing", jobId: id, source: "external", status: "submitted" },
          { name: "Roger Habimana", email: "roger@email.com", phone: "+250788901239", currentPosition: "Marketing Coordinator", jobTitle: "Marketing Coordinator", yearsOfExperience: 1, experienceYears: 1, educationLevel: "Bachelor Degree", summary: "Marketing coordinator growing in digital channels.", skills: ["Social Media", "Content Strategy", "Google Analytics"], certifications: ["Google Analytics"], projects: ["Managed company social media accounts"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Sandra Nyinawumuntu", email: "sandra@email.com", phone: "+250789012349", currentPosition: "Marketing Manager", jobTitle: "Marketing Manager", yearsOfExperience: 5, experienceYears: 5, educationLevel: "MBA", summary: "Marketing manager driving growth for tech companies for 5 years.", skills: ["Digital Marketing", "SEO", "Content Strategy", "Social Media", "Google Analytics", "PPC", "CRM"], certifications: ["Google Digital Marketing", "HubSpot Marketing Hub", "Salesforce Marketing Cloud", "Meta Blueprint Advanced"], projects: ["Rebranding +80% brand recognition", "Built marketing team 0 to 8", "Demand gen 1000+ leads/month"], githubUrl: "", portfolioUrl: "https://sandra.marketing", jobId: id, source: "external", status: "submitted" },
          { name: "Thierry Gasana", email: "tgasana@email.com", phone: "+250780123460", currentPosition: "SEO Specialist", jobTitle: "SEO Specialist", yearsOfExperience: 2, experienceYears: 2, educationLevel: "Bachelor Degree", summary: "SEO specialist focused on organic growth and content strategy.", skills: ["SEO", "Content Strategy", "Google Analytics", "Digital Marketing"], certifications: ["Google Digital Marketing", "SEMrush SEO Certification"], projects: ["Ranked 15 keywords on page 1 Google", "Blog content strategy doubling traffic"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Umutoni Clarisse", email: "umutoni@email.com", phone: "+250781234570", currentPosition: "Social Media Manager", jobTitle: "Social Media Manager", yearsOfExperience: 3, experienceYears: 3, educationLevel: "Bachelor Degree", summary: "Social media manager growing brand audiences across platforms.", skills: ["Social Media", "Content Strategy", "Digital Marketing", "Google Analytics"], certifications: ["Meta Blueprint", "HubSpot Social Media"], projects: ["Grew Instagram from 2k to 30k followers", "Influencer campaign 1M impressions"], githubUrl: "", portfolioUrl: "https://umutoni.marketing", jobId: id, source: "external", status: "submitted" },
          { name: "Valens Nzabarinda", email: "valens@email.com", phone: "+250782345682", currentPosition: "Growth Marketer", jobTitle: "Growth Marketer", yearsOfExperience: 4, experienceYears: 4, educationLevel: "Bachelor Degree", summary: "Growth marketer with data-driven approach to acquisition and retention.", skills: ["Digital Marketing", "SEO", "Content Strategy", "Social Media", "Google Analytics", "PPC", "Email Marketing"], certifications: ["Google Digital Marketing", "HubSpot Growth Marketing", "Meta Blueprint"], projects: ["User acquisition campaign 5k signups", "Retention email sequence 40% churn reduction", "PPC campaigns ROI 3x"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
        ]);
      }

      if (title.toLowerCase().includes("data scientist") || title.toLowerCase().includes("data science")) {
        allApplicants.push(...[
          { name: "Iris Uwase", email: "iris@email.com", phone: "+250789012350", currentPosition: "Data Analyst", jobTitle: "Data Analyst", yearsOfExperience: 3, experienceYears: 3, educationLevel: "MSc Computer Science", summary: "Data scientist with strong ML and statistical analysis background.", skills: ["Python", "Machine Learning", "PostgreSQL", "Docker", "AWS", "TensorFlow"], certifications: ["Google Data Analytics", "AWS Machine Learning Specialty", "TensorFlow Developer"], projects: ["Churn model saving $2M/year", "NLP support ticket classifier", "Demand forecasting system"], githubUrl: "https://github.com/iris", portfolioUrl: "https://iris-data.com", jobId: id, source: "external", status: "submitted" },
          { name: "James Bizimana", email: "james@email.com", phone: "+250780123461", currentPosition: "Junior Data Scientist", jobTitle: "Junior Data Scientist", yearsOfExperience: 1, experienceYears: 1, educationLevel: "BSc Computer Science", summary: "Junior data scientist eager to solve real business problems with ML.", skills: ["Python", "PostgreSQL", "Machine Learning"], certifications: ["Google Data Analytics"], projects: ["Housing price prediction", "Image classification with CNN"], githubUrl: "https://github.com/james", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Karen Ineza", email: "karen@email.com", phone: "+250781234571", currentPosition: "Data Engineer", jobTitle: "Data Engineer", yearsOfExperience: 4, experienceYears: 4, educationLevel: "MSc Computer Science", summary: "Data engineer building production ML systems and data pipelines.", skills: ["Python", "Machine Learning", "PostgreSQL", "Docker", "AWS", "Spark", "Airflow"], certifications: ["AWS Data Analytics", "Google Professional Data Engineer", "Databricks Certified"], projects: ["Real-time pipeline 1M events/day", "ML model serving platform", "Data warehouse migration"], githubUrl: "https://github.com/karen", portfolioUrl: "https://karen.io", jobId: id, source: "external", status: "submitted" },
          { name: "Landry Hakizimana", email: "landry@email.com", phone: "+250782345683", currentPosition: "Machine Learning Engineer", jobTitle: "Machine Learning Engineer", yearsOfExperience: 3, experienceYears: 3, educationLevel: "MSc Computer Science", summary: "ML engineer deploying models to production at scale.", skills: ["Python", "Machine Learning", "Docker", "AWS", "PyTorch", "PostgreSQL"], certifications: ["AWS Machine Learning Specialty", "Deep Learning Specialization"], projects: ["Object detection model in production", "Recommendation system for media platform", "AutoML pipeline"], githubUrl: "https://github.com/landry", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Magali Uwera", email: "magali@email.com", phone: "+250783456793", currentPosition: "Data Analyst", jobTitle: "Data Analyst", yearsOfExperience: 2, experienceYears: 2, educationLevel: "BSc Computer Science", summary: "Data analyst using Python and SQL to drive business insights.", skills: ["Python", "PostgreSQL", "Machine Learning"], certifications: ["Google Data Analytics", "IBM Data Science"], projects: ["Sales dashboard in Tableau", "Customer segmentation analysis"], githubUrl: "https://github.com/magali", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Nelson Niyongabo", email: "nelson@email.com", phone: "+250784567896", currentPosition: "Senior Data Scientist", jobTitle: "Senior Data Scientist", yearsOfExperience: 6, experienceYears: 6, educationLevel: "PhD", summary: "PhD data scientist building ML systems that drive real business value.", skills: ["Python", "Machine Learning", "PostgreSQL", "Docker", "AWS", "Spark", "Airflow", "PyTorch", "Scikit-learn"], certifications: ["AWS Data Analytics", "Google Professional Data Engineer", "Databricks Certified", "Deep Learning Specialization"], projects: ["Fraud detection system saving $5M/year", "Recommendation engine for 5M users", "NLP pipeline processing 10M docs"], githubUrl: "https://github.com/nelson", portfolioUrl: "https://nelson-ml.io", jobId: id, source: "external", status: "submitted" },
        ]);
      }

      if (title.toLowerCase().includes("finance")) {
        allApplicants.push(...[
          { name: "Wanda Uwase", email: "wanda@email.com", phone: "+250785678906", currentPosition: "Accountant", jobTitle: "Accountant", yearsOfExperience: 3, experienceYears: 3, educationLevel: "Bachelor Degree", summary: "Certified accountant with 3 years in financial reporting and compliance.", skills: ["Accounting", "Financial Reporting", "Excel", "QuickBooks", "Budgeting", "Tax Compliance"], certifications: ["CPA Rwanda", "QuickBooks ProAdvisor"], projects: ["Automated payroll system", "Annual financial statements for 3 companies"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Xavier Nkusi", email: "xavier@email.com", phone: "+250786789017", currentPosition: "Finance Assistant", jobTitle: "Finance Assistant", yearsOfExperience: 1, experienceYears: 1, educationLevel: "Bachelor Degree", summary: "Finance graduate with internship experience in financial reporting.", skills: ["Accounting", "Excel", "Budgeting"], certifications: [], projects: ["Monthly budget reports for SME"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Yvonne Mukamana", email: "yvonne@email.com", phone: "+250787890129", currentPosition: "Senior Finance Officer", jobTitle: "Senior Finance Officer", yearsOfExperience: 5, experienceYears: 5, educationLevel: "MBA", summary: "Senior finance officer managing finances for tech companies for 5 years.", skills: ["Accounting", "Financial Reporting", "Excel", "QuickBooks", "Budgeting", "SAP", "Financial Modeling"], certifications: ["CPA Rwanda", "ACCA", "QuickBooks ProAdvisor", "SAP Finance Module"], projects: ["Audit prep $10M revenue company", "3-year financial model for board", "25% cost reduction through analysis"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Zephyrin Nkurunziza", email: "zephyrin@email.com", phone: "+250788901240", currentPosition: "Finance Analyst", jobTitle: "Finance Analyst", yearsOfExperience: 2, experienceYears: 2, educationLevel: "Bachelor Degree", summary: "Finance analyst with strong Excel and financial modeling skills.", skills: ["Accounting", "Financial Reporting", "Excel", "Budgeting", "Financial Modeling"], certifications: ["CPA Rwanda (in progress)", "Excel Advanced Certification"], projects: ["Financial model for startup valuation", "Monthly MIS reports for management"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Adeline Uwingabire", email: "adeline@email.com", phone: "+250789012351", currentPosition: "Tax Officer", jobTitle: "Tax Officer", yearsOfExperience: 3, experienceYears: 3, educationLevel: "Bachelor Degree", summary: "Tax specialist with strong compliance and financial reporting background.", skills: ["Accounting", "Financial Reporting", "Excel", "QuickBooks", "Budgeting"], certifications: ["CPA Rwanda", "RRA Tax Certificate"], projects: ["Filed taxes for 20+ companies", "Tax compliance training for finance team"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Bertrand Habimana", email: "bertrand@email.com", phone: "+250780123462", currentPosition: "CFO", jobTitle: "CFO", yearsOfExperience: 8, experienceYears: 8, educationLevel: "MBA", summary: "CFO with 8 years leading finance functions in East Africa.", skills: ["Accounting", "Financial Reporting", "Excel", "QuickBooks", "Budgeting", "SAP", "Financial Modeling", "Investor Relations"], certifications: ["CPA Rwanda", "ACCA", "CFA Level 2", "SAP Finance"], projects: ["IPO preparation for regional bank", "Secured $5M Series A financing", "Built finance team of 12 people"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
        ]);
      }

      if (title.toLowerCase().includes("hr") || title.toLowerCase().includes("human resources")) {
        allApplicants.push(...[
          { name: "Zacharie Nsengimana", email: "zacharie@email.com", phone: "+250786789018", currentPosition: "HR Officer", jobTitle: "HR Officer", yearsOfExperience: 3, experienceYears: 3, educationLevel: "Bachelor Degree", summary: "HR officer with 3 years in recruitment, onboarding and employee relations.", skills: ["Recruitment", "Onboarding", "Employee Relations", "HR Policies", "Payroll", "Performance Management"], certifications: ["SHRM-CP", "HR Management Certificate"], projects: ["Hired 50+ employees in 2 years", "Onboarding program reducing time-to-productivity 30%"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Amina Uwimana", email: "amina@email.com", phone: "+250787890130", currentPosition: "HR Assistant", jobTitle: "HR Assistant", yearsOfExperience: 1, experienceYears: 1, educationLevel: "Bachelor Degree", summary: "HR assistant growing in talent acquisition and employee relations.", skills: ["Recruitment", "Onboarding", "HR Policies"], certifications: [], projects: ["Assisted hiring 20 candidates"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Bernard Twahirwa", email: "bernard@email.com", phone: "+250788901241", currentPosition: "HR Manager", jobTitle: "HR Manager", yearsOfExperience: 6, experienceYears: 6, educationLevel: "MBA", summary: "HR manager building people-first cultures in fast-growing companies.", skills: ["Recruitment", "Onboarding", "Employee Relations", "HR Policies", "Payroll", "Performance Management", "L&D", "HRIS"], certifications: ["SHRM-SCP", "CIPD Level 5", "Workday HCM", "LinkedIn Recruiter"], projects: ["Built HR department from scratch", "Reduced turnover 45% in 2 years", "HRIS for 300-person company"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Celestine Mukamurera", email: "celestine@email.com", phone: "+250789012352", currentPosition: "Talent Acquisition Specialist", jobTitle: "Talent Acquisition Specialist", yearsOfExperience: 2, experienceYears: 2, educationLevel: "Bachelor Degree", summary: "Talent specialist focused on sourcing and hiring top tech talent.", skills: ["Recruitment", "Onboarding", "Employee Relations", "HR Policies"], certifications: ["LinkedIn Recruiter Certification"], projects: ["Sourced 30 tech candidates in 3 months", "Set up ATS for startup"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Dieudonné Nshimiyimana", email: "dieudonne@email.com", phone: "+250780123463", currentPosition: "HR Generalist", jobTitle: "HR Generalist", yearsOfExperience: 3, experienceYears: 3, educationLevel: "Bachelor Degree", summary: "HR generalist handling full employee lifecycle from hire to retire.", skills: ["Recruitment", "Onboarding", "Employee Relations", "HR Policies", "Payroll"], certifications: ["SHRM-CP", "HR Analytics Certificate"], projects: ["Employee engagement survey and action plan", "Payroll migration to new system"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
          { name: "Esperance Kayitesi", email: "esperance@email.com", phone: "+250781234572", currentPosition: "HR Director", jobTitle: "HR Director", yearsOfExperience: 10, experienceYears: 10, educationLevel: "MBA", summary: "HR Director with 10 years shaping HR strategy across East Africa.", skills: ["Recruitment", "Onboarding", "Employee Relations", "HR Policies", "Payroll", "Performance Management", "L&D", "HRIS", "Organizational Design"], certifications: ["SHRM-SCP", "CIPD Level 7", "Workday HCM", "LinkedIn Recruiter", "OD Practitioner"], projects: ["HR transformation for 500-person organization", "Regional talent strategy for 5 countries", "DEI program improving diversity metrics 60%"], githubUrl: "", portfolioUrl: "", jobId: id, source: "external", status: "submitted" },
        ]);
      }
    });

    if (allApplicants.length === 0) {
      console.log("No matching jobs found for applicant templates. Adding generic applicants to first job...");
    }

    await Applicant.insertMany(allApplicants);
    console.log(`Created ${allApplicants.length} applicants across ${jobs.length} jobs`);
    console.log("Done! Open your app and go to Applicants to see them.");
    process.exit(0);
  } catch (error) {
    console.error("Seed failed:", error);
    process.exit(1);
  }
};

seed();
